### ISSUE TITLE
supporting large numbers of connections

### ISSUE THREAD

**Issue by jlatt** [jlatt/ergonomadic#27]
IRC protocol specifies a clunky server federation system. It doesn't seem very useful in the modern world given the capabilities of available hardware.

One alternative is to create an IRC forwarding proxy. It would transmit traffic to the real server as tagged messages so that replies can be distributed to the matching connection on the proxy side.

**Comment by edmund-huber** [comment]
https://github.com/edmund-huber/ergonomadic/issues/2 <3
